import type { Metadata } from "next";
import { Lexend, Nunito, Poppins } from "next/font/google";
import "../globals.css";
import Provider from "@/components/providers/Provider";

export const poppins = Poppins({ subsets: ["latin"], variable: "--font-sans", weight: ["400","500","600","700","800","900"] });
export const lexend = Lexend({ subsets: ["latin"], variable: "--font-sans-2", weight: ["400","500","600","700","800","900"] });
export const nunito = Nunito({ subsets: ["latin"], variable: "--font-sans-3", weight: ["400","500","600","700","800","900"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${poppins.variable} ${lexend.variable} ${nunito.variable}`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
